### ISSUE TITLE
Is there anyone who can use this plugin ?

### ISSUE THREAD

**Issue by ninet9aaaa** [Baedda/floating-form-labels#25]
cant get it to work, spend many hours, im dev for more than a decade.
How the hell would i import directly scss ? why no one scss converter can convert to this scss to css ?
Why ????????
Why the hell did you include scss, and not css ? It is crazy

**Comment by Baedda** [comment]
@ninet9aaaa I am sorry to hear that you have so much struggle with getting the plugin work. I am using this plugin in many of my projects for years now and don't have any trouble. Could you please explain what exactly you have tried? Have you read the documentation about how to work with the scss mixin?
https://github.com/Baedda/floating-form-labels#sass

**Comment by tomm1996** [comment]
I think @ninet9aaaa wants a .css file to include in the dist because he does not use scss.

@ninet9aaaa 
if you want to convert this using an online compiler, you have to apply the mixin to your desired class:

copy the scss/_floating-form-labels.scss into your converter and use the mixin like this and it will compile:

```
.ffl-wrapper {
    @include floating-form-labels(10px, 10px);
}
```

![image](https://user-images.githubusercontent.com/4152001/59510652-89e11d80-8eb4-11e9-8d1b-16a8f976aee7.png)

**Comment by Baedda** [comment]
I am closing this because @ninet9aaaa is not answering anymore.
